#### Plugins ########
plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/core/plugin_config.yaml'

#### Channel Fusions ########
pointcloud_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'average'          # 'average' fusion is used for channels not listed here

image_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'exponential'      # 'exponential' fusion is used for channels not listed here
  feat_.*: 'exponential'      # 'exponential' fusion is also used for any channel starting with 'feat_' Regular expressions can be used for channel names

#### Subscribers ########
# subscribers:
#  pointcloud_sensor_name:
#    topic_name: '/carla/ego_vehicle/velodyne'
#    data_type:  pointcloud  # pointcloud or image

#  image_sensor_name:
#    topic_name: '/carla/ego_vehicle/camera_front/image_rgb'
#    data_type:  image  # pointcloud or image
#    camera_info_topic_name: '/carla/ego_vehicle/camera_front/camera_info'


subscribers:
  # pointcloud_sensor_name:
  #   topic_name: '/carla/ego_vehicle/velodyne'
  #   data_type:  pointcloud  # pointcloud or image
  front_cam:
    topic_name: '/camera/depth/points_front'
    data_type: pointcloud
  rear_cam:
    topic_name: '/camera/depth/points_rear'
    data_type: pointcloud
  left_cam:
    topic_name: '/camera/depth/points_left'
    data_type: pointcloud
  right_cam:
    topic_name: '/camera/depth/points_right'
    data_type: pointcloud
  color_cam_front: # for color camera
    topic_name: '/carla/ego_vehicle/semantic_camera_front/image_rgb'
    camera_info_topic_name: '/carla/ego_vehicle/semantic_camera_front/camera_info'
    data_type: image
  color_cam_rear: # for color camera
    topic_name: '/carla/ego_vehicle/semantic_camera_rear/image_rgb'
    camera_info_topic_name: '/carla/ego_vehicle/semantic_camera_rear/camera_info'
    data_type: image
  color_cam_left: # for color camera
    topic_name: '/carla/ego_vehicle/semantic_camera_left/image_rgb'
    camera_info_topic_name: '/carla/ego_vehicle/semantic_camera_left/camera_info'
    data_type: image
  color_cam_right: # for color camera
    topic_name: '/carla/ego_vehicle/semantic_camera_right/image_rgb'
    camera_info_topic_name: '/carla/ego_vehicle/semantic_camera_right/camera_info'
    data_type: image
  # semantic_cam: # for semantic images
  #   topic_name: '/semantic_image/semantic_image'
  #   camera_info_topic_name: '/semantic_image/carla/ego_vehicle/camera_front/camera_info_resized'
  #   channel_info_topic_name: '/semantic_image/channel_info'
  #   data_type: image

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['rgb', 'elevation', 'traversability', 'min_filter', 'inpaint', 'rgb2', 'elevation2', 'traversability2', 'combined_cost']
    basic_layers: ['min_filter']
    # layers: ['rgb', 'elevation', 'min_filter', 'inpaint']
    # basic_layers: ['min_filter']
    fps: 10.0