# Settings of the plugins. (The plugins should be stored in script/plugins)

# min_filter fills in minimum value around the invalid cell.
min_filter:                                   
  enable: True                                # weather to load this plugin
  fill_nan: False                             # Fill nans to invalid cells of elevation layer.
  is_height_layer: True                       # If this is a height layer (such as elevation) or not (such as traversability)
  layer_name: "min_filter"                    # The layer name.
  extra_params:                               # This params are passed to the plugin class on initialization.
    dilation_size: 1                         # The patch size to apply
    iteration_n: 30                           # The number of iterations
# Apply smoothing.
smooth_filter:
  enable: False
  fill_nan: False
  is_height_layer: True
  layer_name: "smooth"
  extra_params:
    input_layer_name: "min_filter"
# Apply inpainting using opencv
inpainting:
  enable: True
  fill_nan: False
  is_height_layer: True
  layer_name: "inpaint"
  extra_params:
    method: "telea"                           # telea or ns
# Apply smoothing for inpainted layer
erosion:
  enable: False
  fill_nan: False
  is_height_layer: False
  layer_name: "erosion"
  extra_params:
    input_layer_name: "traversability"
    dilation_size: 3
    iteration_n: 20
    reverse: True
semantic_filter:
  enable: False
  fill_nan: False
  is_height_layer: False
  layer_name: "max_categories"
  extra_params:
    input_layer_name: "class"
    category_n: 3                            # number of categories to keep
    min_prob: 0.5                            # minimum probability to keep the category
    use_probability: True                     # if true, use probability to select the category. otherwise, use count.
    use_height: False                         # if true, use height to select the category. otherwise, use count.
    height_thresh: 0.2                        # if use_height is true, this threshold is used.
    height_diff_thresh: 0.1                   # if use_height is true, this threshold is used.
elevation2:
  enable: True
  type: "example"
  fill_nan: False
  is_height_layer: True
  layer_name: "elevation2"  # This name is passed to the __call__ method
  extra_params:
    value: 1.0                           # This is an example parameter
rgb2:
  enable: True
  type: "example"
  fill_nan: False
  is_height_layer: False  # RGB is not a height layer
  layer_name: "rgb2"
  extra_params:
    value: 2.0                           # This is an example parameter
traversability2:
  enable: True
  type: "traversability2"
  fill_nan: False
  is_height_layer: False
  layer_name: "traversability2"
  extra_params:
    input_layer_name: "elevation2"
combined_cost:
  enable: True
  type: "combined_cost"
  fill_nan: False
  is_height_layer: False   
  layer_name: "combined_cost" 
  extra_params:
    scale_factor: 0.5    